---
# 1. This is the "Safety Gate"
- name: Stop if server is not Keycloak, Clickhouse, or Opensearch
  ansible.builtin.meta: end_host
  when: 
    - "'keycloak' not in group_names"
    - "'clickhouse' not in group_names"
    - "'opensearch' not in group_names"

# 2. Only if the server survives the gate, load vars and continue
- name: Load service variables
  ansible.builtin.include_vars: vars/main.yml

- include_tasks: install.yml
- include_tasks: config.yml
- include_tasks: service.yml
