---
- name: Check if host is a valid consul service node
  ansible.builtin.set_fact:
    is_valid_node: "{{ ('keycloak' in group_names) or ('clickhouse' in group_names) or ('opensearch' in group_names) }}"

- name: Stop execution if not a valid node
  ansible.builtin.meta: end_host
  when: not is_valid_node
  
- name: Load service variables
  ansible.builtin.include_vars: vars/main.yml

- include_tasks: install.yml
- include_tasks: config.yml
- include_tasks: service.yml
