- name: Create consul service
  copy:
    dest: /etc/systemd/system/consul.service
    content: |
      [Unit]
      Description=Consul Agent
      After=network.target

      [Service]
      User={{ consul_user }}
      ExecStart={{ consul_install_dir }}/consul agent -config-dir={{ consul_config_dir }}
      Restart=always

      [Install]
      WantedBy=multi-user.target


- name: Enable and Start Consul Service
  ansible.builtin.systemd:
    name: consul
    enabled: yes
    state: started
    daemon_reload: yes
